backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
  repo: maty535/urbarSolivar # Zmeňte na váš názov (napr. jozko/moj-web)
  
media_folder: 'assets/uploads'

collections:
  - name: 'oznamy'
    label: 'Oznamy'
    folder: '_posts/'
    create: true # Umožní zákazníkovi pridať nový príspevok
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Formát názvu súboru
    fields:
      - { name: Title }